TI-Sklep/Controllers/FIlmyController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using TI_Sklep.DAL;
using TI_Sklep.Models;
using TI_Sklep.ViewModels;

namespace TI_Sklep.Controllers
{
    public class FilmyController : Controller
    {
        FilmyContext db;
        IWebHostEnvironment hostEnvironment;

        public FilmyController(FilmyContext db, IWebHostEnvironment hostEnvironment)
        {
            this.db = db;
            this.hostEnvironment = hostEnvironment;
        }

        public IActionResult ListaFilmow(string nazwaKategorii)
        {
            KategoriaViewModels vm = new KategoriaViewModels();

            var kategoria = db.Kategorie.Include("Filmy").Where(k => k.Nazwa == nazwaKategorii).Single();
            var filmy = kategoria.Filmy.ToList();


            vm.FilmyKategorii = filmy;
            vm.Kategoria = kategoria;
            vm.FilmyTop3Najnowsze = db.Filmy.OrderByDescending(f => f.DataDodania).Take(3);

            return View(vm);
        }

        public IActionResult Szczegoly(int idFilmu)
        {
            var kategoria = db.Kategorie.Find(db.Filmy.Find(idFilmu).KategoriaId);
            var film = db.Filmy.Find(idFilmu);

            return View(film);
        }

        public IActionResult Wszystkie()
        {
            return View(db.Filmy.ToList());
        }
        [HttpGet]
         public IActionResult DodajFilm()
        {
            var model = new DodawanieFilmowViewModels();
            model.Kategorie = db.Kategorie.ToList();
            return View(model);
        }
        [HttpPost]
        public IActionResult DodajFilm(DodawanieFilmowViewModels obj)
        {
            var posterPath = Path.Combine(hostEnvironment.WebRootPath, "content");
            var posterName = Guid.NewGuid() + "_" + obj.Plakat.FileName;
            var filePath = Path.Combine(posterPath, posterName);
            obj.Plakat.CopyTo(new FileStream(filePath, FileMode.Create));
            obj.Film.Plakat = posterName;

            obj.Film.DataDodania = DateTime.Now;
            db.Filmy.Add(obj.Film);
            db.SaveChanges();
            return RedirectToAction("Wszystkie");
        }
        [HttpGet]
        public IActionResult EdytujFilm(int id)
        {
            var kategoria = db.Kategorie.Find(db.Filmy.Find(id).KategoriaId);
            var film = db.Filmy.Where(f => f.Id == id).FirstOrDefault();
            return View(film);
        }

        [HttpPost]
        public IActionResult EdytujFilm(Film film)
        {
            var edytowany = db.Filmy.Where(f => f.Id == film.Id).FirstOrDefault();
            edytowany.Tytul = film.Tytul;
            edytowany.Rezyser = film.Rezyser;
            edytowany.Opis = film.Opis;
            edytowany.Cena = film.Cena;
            edytowany.DataDodania = film.DataDodania;

            db.SaveChanges();

            return RedirectToAction("Szczegoly", new { idFilmu = film.Id });
        }

        [HttpPost]
        public IActionResult Szukaj(string fraza)
        {
            var filmy = from f in db.Filmy select f;

            filmy = filmy.Where(f => f.Tytul.ToLower().Contains(fraza.ToLower()));

            ViewBag.szukanie = fraza;

            return View(filmy.ToList());
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

TI-Sklep/Controllers/KoszykController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TI_Sklep.DAL;
using TI_Sklep.Infrastructure;
using TI_Sklep.Models;
using TI_Sklep.ViewModels;

namespace TISklep.Controllers
{
    public class KoszykController : Controller
    {
        FilmyContext db;

        public KoszykController(FilmyContext db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            var cart = CartManager.GetItems(HttpContext.Session);
            ViewBag.total = CartManager.GetCartValue(HttpContext.Session);
            return View(cart);
        }

        public IActionResult DodajDoKoszyka(int idFilmu)
        {
            CartManager.AddToCart(HttpContext.Session, db, idFilmu);

            return RedirectToAction("Index");
        }

        public IActionResult UsunZKoszyka(int id)
        {
            var model = new UsuwanieElementowKosztkaViewModels()
            {
                Id = id,
                Ilosc = CartManager.RemovefromCart(HttpContext.Session, id),
                WartoscKoszyka = CartManager.GetCartValue(HttpContext.Session),
                IloscTotal = CartManager.GetCartQuantity(HttpContext.Session)
            };

            return Json(model);
        }
    }
}

TI-Sklep/ViewComponents/FilmyKategoriiViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TI_Sklep.DAL;

namespace TI_Sklep.ViewComponents
{
    public class FilmyKategoriiViewComponent : ViewComponent
    {
        FilmyContext db;

        public FilmyKategoriiViewComponent(FilmyContext db)
        {
            this.db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync(string nazwaKategorii)
        {
        var kategoria = db.Kategorie.Include("Filmy").Where(k => k.Nazwa == nazwaKategorii).Single();
        var filmy = kategoria.Filmy.ToList();

            return await Task.FromResult((IViewComponentResult) View("_FilmyKategorii", filmy));
        }
    }
}

TI-Sklep/Views/Filmy/DodajFilm.cshtml
@model TI_Sklep.ViewModels.DodawanieFilmowViewModels

@using (Html.BeginForm("DodajFilm", "Filmy", FormMethod.Post, new { enctype="multipart/form-data"}))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Film.Tytul, "Podaj tytuł: ")
        @Html.TextBoxFor(m => m.Film.Tytul, new { @required = true, @class="form-control"})
    </div>
    
    <div class="form-group">
        @Html.LabelFor(m => m.Film.Rezyser, "Podaj reżysera: ")
        @Html.TextBoxFor(m => m.Film.Rezyser, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Film.Opis, "Podaj opis: ")
        @Html.TextAreaFor(m => m.Film.Opis, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Plakat, "Wybierz Plakat:")
        @Html.TextBoxFor(m => m.Plakat, new { @type = "file", @class = "form-control-file" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Film.Dlugosc, "Podaj długość filmu: ")
        @Html.TextAreaFor(m => m.Film.Dlugosc, new { @class = "form-control" })
    </div>

    <div class="form-check">
        @foreach (var kategoria in Model.Kategorie)
        {
            @Html.RadioButtonFor(m => m.Film.KategoriaId, kategoria.Id, new { @class="form-cheack-input"})
            @kategoria.Nazwa
        }
    </div>
    <div class="form-group"><input type="submit" value="Wyślij" class="btn btn-primary" /></div>
}

TI-Sklep/Views/Filmy/EdytujFilm.cshtml
@model TI_Sklep.Models.Film

@using (Html.BeginForm("EdytujFilm", "Filmy", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(f => f.Plakat)
    @Html.HiddenFor(f => f.KategoriaId)
    <table>
        <tr>
            <td>
                <h1>@Model.Kategoria.Nazwa</h1>
                @await Component.InvokeAsync("FilmyKategorii", new { nazwaKategorii = Model.Kategoria.Nazwa })
            </td>
            <td>
                <ul>
                    <li>Tytuł: @Html.TextBoxFor(f => f.Tytul)</li>
                    <li>Reżyser: @Html.TextBoxFor(f => f.Rezyser) </li>
                    <li>Opis: @Html.TextAreaFor(f => f.Opis)</li>
                    <li>Cena: @Html.TextBoxFor(f => f.Cena)</li>
                    <li>Data produkcji: @Html.TextBoxFor(f => f.DataDodania, new { @type = "datetime" })</li>
                </ul>
            </td>
        </tr>
    </table>
    <button type="submit">Zapisz</button>
}

TI-Sklep/Views/Filmy/ListaFilmow.cshtml
@model TI_Sklep.ViewModels.KategoriaViewModels
    @{
        ViewData["Title"] = "Lista z Kategorii";
    }
    <h1>@Model.Kategoria.Nazwa - @Model.Kategoria.Opis</h1>
<table>
    <tr class="banner">
        @foreach (var film in Model.FilmyTop3Najnowsze)
        {
        <td class="film">
            <h3>@film.Tytul</h3>
            <p>@film.Opis</p>
            <img src="~/content/@film.Plakat" />
            <p>@film.Opis</p>
        </td>
        }
    </tr>
</table>
    <table>
        <thead>
            <tr>
                <th>Tytul filmu</th>
                <th>Rezyser</th>
                <th>Data dodania</th>
                <th>Cena</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var film in Model.FilmyKategorii)
            {
            <tr>
                <td>@film.Tytul</td>
                <td>@film.Rezyser</td>
                <td>@film.DataDodania.Value.Date.ToString("dd MMMM yyyy")</td>
                <td>@film.Cena</td>
                <td>
                    <a href="@Url.Action("Szczegoly" , "Filmy", new {idFilmu=film.Id })">&#128269;</a>
                </td>
                <td>
                    <a href="@Url.Action("DodajDoKoszyka", "Koszyk", new { idFilmu = film.Id })">
                        &#128722;
                    </a>
                </td>
            </tr>
            }
        </tbody>
    </table>

TI-Sklep/Views/Filmy/Szczegoly.cshtml
@Model TI_Sklep.Models.Film

@{
    ViewData["Title"] = "Lista Kategorii";
}

<table>
    <tr>
        <td>
        <h1>@Model.Kategoria.Nazwa</h1>
        @await Component.InvokeAsync("FilmyKategorii", new { nazwaKategorii = Model.Kategoria.Nazwa})</td>
        <td>
            <ul>
                <li>Tytul: @Model.Tytul</li>
                <li>Rezyser: @Model.Rezyser</li>
                <li>Opis: @Model.Opis</li>
                <li>Cena: @Model.Cena zł</li>
                <li>Data Dodania: @Model.DataDodania</li>
                <li>Dlugosc: @Model.Dlugosc</li>
            </ul>
            <button onclick="location.href='@Url.Action("EdytujFilm", "Filmy", new { id = Model.Id })'">Edytuj</button>
        </td>
    </tr>
</table>

TI-Sklep/Views/Filmy/Szukaj.cshtml
@model IEnumerable<TI_Sklep.Models.Film>

    <h3>Filmy zawierające frazę: @ViewBag.szukanie </h3>

    <table class="table">
        <thead>
            <tr>
                <th>Tytuł filmu</th>
                <th>Reżyser</th>
                <th>Data dodania</th>
                <th>Cena</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var film in Model)
            {
                <tr>
                    <td>@film.Tytul</td>
                    <td>@film.Rezyser</td>
                    <td>@film.DataDodania</td>
                    <td>@film.Cena</td>
                    <td>
                        <a href="@Url.Action("Szczegoly", "Filmy", new { idFilmu = film.Id })">&#128270;</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

TI-Sklep/Views/Filmy/Wszystkie.cshtml
@model IEnumerable<TI_Sklep.Models.Film>

<div class="wszystkie-filmy">
    <ul>
        @foreach (var film in Model)
        {
            <li class="pojedynczy-film">
                <a href="@Url.Action("Szczegoly" , "Filmy", new {idFilmu=film.Id })"><img src="~/content/@film.Plakat" /></a>
            </li>
        }
    </ul>
</div>